var role_privilege = {
		/**
		 *数据 
		 */
		data:{
			role:{
				name:'',
				rid:''
			},
			checkedStr:''//被选中的权限树上的复选框的id的值
		},
		/**
		 *存放操作 
		 */
		opt:{
			/**
			 *关于div的操作 
			 */
			divOpt:{
				//显示被隐藏的的div
				showDiv:function(){
					$("div:hidden").show();
				}
			},
			/**
			 *关于角色的操作 
			 */
			roleOpt:{
				
			},
			roleTree:{
				
			}
		},
		/**
		 *初始化 
		 */
		init:{
			//初始化数据
			initData:function(){
				
			},
			//初始化事件
			initEvent:function(){
				/**
				 *给设置权限添加click事件 
				 */
				$("a").each(function(){
					if($(this).text()=="设置权限"){
						$(this).css("cursor","pointer");
						$(this).unbind("click");
						$(this).bind("click",function(){
							/**
							 *1.显示隐藏的div 
							 * 2.加载权限树
							 *3.对角色原来的有的权限进行回显
							 */
							role_privilege.opt.divOpt.showDiv();
						})
					}
				});
			}
		}
};
$().ready(function(){
	role_privilege.init.initEvent();
});