var role_privilege = {
		/**
		 *数据 
		 */
		data:{
			role:{
				name:'',
				rid:''
			},
			checkedStr:''//被选中的权限树上的复选框的id的值
		},
		/**
		 *存放操作 
		 */
		opt:{
			/**
			 *关于div的操作 
			 */
			divOpt:{
				//显示被隐藏的的div
				showDiv:function(){
					$("div:hidden").show();
				}
			},
			/**
			 *关于角色的操作 
			 */
			roleOpt:{
				showRoleName:function(){
					$("#roleImage").text("角色："+role_privilege.data.role.name)
				}
			},
			/**
			 *权限树 
			 */
			privilegeTree:{
				setting:{
					isSimpleData:true,
					treeNodeKey:"id",
					treeNodeParentKey:"pid",
					showLine:"true",
					root:{
						isRoot:true,
						nodes:{}
					},
					checkable:true
				},
				loadPrivilegeTree:function(){
					/**
					 *第三个参数为回调函数 
					 *该回调函数是由服务器发的，并且在readyState的值为4，status的值为200的情况下触发的
					 */
					$.post("privilegeAction_showPrivilegeTree.action",null,function(data){
						$("#privilegeTree").zTree(role_privilege.opt.privilegeTree.setting,data);
						/**
						 *设置显示权限树，隐藏loading 
						 */
						$("#loading").hide();
						$("#privilegeTree").show();
					});
				}
			}
		},
		/**
		 *初始化 
		 */
		init:{
			//初始化数据
			initData:function(){
				var name = $(this).parent().siblings("td:first").text();
				var rid = $(this).parent().siblings("input[type='hidden']").attr("value");
				role_privilege.data.role.name=name;
				role_privilege.data.role.rid=rid;
			},
			//初始化事件
			initEvent:function(){
				/**
				 *给设置权限添加click事件 
				 */
				$("a").each(function(){
					if($(this).text()=="设置权限"){
						$(this).css("cursor","pointer");
						$(this).unbind("click");
						$(this).bind("click",function(){
							/**
							 *1.显示隐藏的div 
							 * 2.加载权限树
							 *3.对角色原来的有的权限进行回显
							 */
							role_privilege.opt.divOpt.showDiv();
							//调用initData给Role的rid和name赋值
							role_privilege.init.initData.call(this);
							//动态显示角色名称
							role_privilege.opt.roleOpt.showRoleName();
							/**
							 *设置显示loading，隐藏权限树 
							 */
							$("#loading").show();
							$("#privilegeTree").hide();
							//加载权限树
							role_privilege.opt.privilegeTree.loadPrivilegeTree();
						});
					}
				});
			}
		}
};
$().ready(function(){
	role_privilege.init.initEvent();
});